language: node_js
node_js: 9.4.0
services: postgresql
before_script:
- psql -c 'create database palettepicker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 4MEFhPYt8bCeayYSkE5ebSNiH+CvzWfxQDKUPxJ9yomysjvQcnP5Xf8N5L7W3gRlTKfWecjqTql8IinhCLzG0IOzPJinR0EdPQa/ijUHyEvmZE2DKJtc71yIz28INnaFaOjREn3Q+b1B3sReCZR6VaU+9p1pmnOIfbsWLxDlItpwW9R9Na4+aONBwoMaIb/gibjY9TiImsudg0pfAM2DTcmCeOHGqQpeLfGG9jcucmtOjgs7of7VYoVy9q5qp9daVkixHAz4mHONL5Y/1n4PYi6JF1RearBiJvYh4n7NgIKLUfsZM15ouFPzb56ywht3mK8qtWhSS0OVxmZh6BSLHexXkRpIfM/EoGXqMog4ZeG5AAJtm2q9hb27aLWjAvOBeVrbUgbXsreCnPh0nRAiUkZ9bM3qfMcmp9vi6/uMwjMqeDtse2wbTjvIML6V5g/yACjnYUjz2lZ3PjdpIAC8KERbEwzOCTmnb6ZD4JBVvNCvVvz3Bw+10/PufqnuAKE8vPQS1vBIQslG3EiNYC1K9mGqf/Xik6S+OveKR1F/WPOAw3fLPTJdwfsJyE72IwdsbRAKyH2EdN9S6wPCewh+706DkwoS4SAwtYpwVLUdXa5i9vRwEbtYukGTumzJUfPgYUTKZl0rvwSpfGS5ZYo4iufigpEJxTstIORm5HBEbns=
  app: helens-janky-colors
  skip_cleanup: true
